// Complete list of countries with coordinates
// Data sourced from standard geographic databases

export const ALL_COUNTRIES = [
    // Africa
    { name: "Algeria", lat: 28.034, lon: 1.659, code: "DZA", region: "Africa" },
    { name: "Angola", lat: -11.203, lon: 17.874, code: "AGO", region: "Africa" },
    { name: "Benin", lat: 9.308, lon: 2.316, code: "BEN", region: "Africa" },
    { name: "Botswana", lat: -22.328, lon: 24.685, code: "BWA", region: "Africa" },
    { name: "Burkina Faso", lat: 12.238, lon: -1.561, code: "BFA", region: "Africa" },
    { name: "Burundi", lat: -3.373, lon: 29.919, code: "BDI", region: "Africa" },
    { name: "Cameroon", lat: 7.370, lon: 12.354, code: "CMR", region: "Africa" },
    { name: "Cape Verde", lat: 16.002, lon: -24.013, code: "CPV", region: "Africa" },
    { name: "Central African Republic", lat: 6.611, lon: 20.939, code: "CAF", region: "Africa" },
    { name: "Chad", lat: 15.454, lon: 18.732, code: "TCD", region: "Africa" },
    { name: "Comoros", lat: -11.645, lon: 43.333, code: "COM", region: "Africa" },
    { name: "DR Congo", lat: -4.038, lon: 21.759, code: "COD", region: "Africa" },
    { name: "Djibouti", lat: 11.825, lon: 42.590, code: "DJI", region: "Africa" },
    { name: "Egypt", lat: 26.821, lon: 30.802, code: "EGY", region: "Africa" },
    { name: "Equatorial Guinea", lat: 1.651, lon: 10.268, code: "GNQ", region: "Africa" },
    { name: "Eritrea", lat: 15.179, lon: 39.782, code: "ERI", region: "Africa" },
    { name: "Eswatini", lat: -26.522, lon: 31.466, code: "SWZ", region: "Africa" },
    { name: "Ethiopia", lat: 9.145, lon: 40.489, code: "ETH", region: "Africa" },
    { name: "Gabon", lat: -0.804, lon: 11.609, code: "GAB", region: "Africa" },
    { name: "Gambia", lat: 13.443, lon: -15.310, code: "GMB", region: "Africa" },
    { name: "Ghana", lat: 7.946, lon: -1.023, code: "GHA", region: "Africa" },
    { name: "Guinea", lat: 9.946, lon: -9.697, code: "GIN", region: "Africa" },
    { name: "Guinea-Bissau", lat: 11.804, lon: -15.180, code: "GNB", region: "Africa" },
    { name: "Ivory Coast", lat: 7.540, lon: -5.547, code: "CIV", region: "Africa" },
    { name: "Kenya", lat: -0.023, lon: 37.906, code: "KEN", region: "Africa" },
    { name: "Lesotho", lat: -29.610, lon: 28.233, code: "LSO", region: "Africa" },
    { name: "Liberia", lat: 6.428, lon: -9.429, code: "LBR", region: "Africa" },
    { name: "Libya", lat: 26.335, lon: 17.229, code: "LBY", region: "Africa" },
    { name: "Madagascar", lat: -18.767, lon: 46.869, code: "MDG", region: "Africa" },
    { name: "Malawi", lat: -13.254, lon: 34.302, code: "MWI", region: "Africa" },
    { name: "Mali", lat: 17.570, lon: -3.996, code: "MLI", region: "Africa" },
    { name: "Mauritania", lat: 21.008, lon: -10.941, code: "MRT", region: "Africa" },
    { name: "Mauritius", lat: -20.348, lon: 57.552, code: "MUS", region: "Africa" },
    { name: "Morocco", lat: 31.792, lon: -7.092, code: "MAR", region: "Africa" },
    { name: "Mozambique", lat: -18.666, lon: 35.530, code: "MOZ", region: "Africa" },
    { name: "Namibia", lat: -22.958, lon: 18.491, code: "NAM", region: "Africa" },
    { name: "Niger", lat: 17.607, lon: 8.081, code: "NER", region: "Africa" },
    { name: "Nigeria", lat: 9.082, lon: 8.675, code: "NGA", region: "Africa" },
    { name: "Republic of the Congo", lat: -0.228, lon: 15.827, code: "COG", region: "Africa" },
    { name: "Rwanda", lat: -1.940, lon: 29.874, code: "RWA", region: "Africa" },
    { name: "Senegal", lat: 14.497, lon: -14.452, code: "SEN", region: "Africa" },
    { name: "Sierra Leone", lat: 8.461, lon: -11.779, code: "SLE", region: "Africa" },
    { name: "Somalia", lat: 5.152, lon: 46.199, code: "SOM", region: "Africa" },
    { name: "South Africa", lat: -30.559, lon: 22.937, code: "ZAF", region: "Africa" },
    { name: "South Sudan", lat: 6.877, lon: 31.307, code: "SSD", region: "Africa" },
    { name: "Sudan", lat: 12.862, lon: 30.217, code: "SDN", region: "Africa" },
    { name: "Tanzania", lat: -6.369, lon: 34.889, code: "TZA", region: "Africa" },
    { name: "Togo", lat: 8.620, lon: 0.824, code: "TGO", region: "Africa" },
    { name: "Tunisia", lat: 33.887, lon: 9.537, code: "TUN", region: "Africa" },
    { name: "Uganda", lat: 1.373, lon: 32.290, code: "UGA", region: "Africa" },
    { name: "Zambia", lat: -13.134, lon: 27.849, code: "ZMB", region: "Africa" },
    { name: "Zimbabwe", lat: -19.015, lon: 29.154, code: "ZWE", region: "Africa" },

    // Asia
    { name: "Afghanistan", lat: 33.939, lon: 67.710, code: "AFG", region: "Asia" },
    { name: "Armenia", lat: 40.069, lon: 45.038, code: "ARM", region: "Asia" },
    { name: "Azerbaijan", lat: 40.143, lon: 47.577, code: "AZE", region: "Asia" },
    { name: "Bahrain", lat: 26.066, lon: 50.558, code: "BHR", region: "Asia" },
    { name: "Bangladesh", lat: 23.685, lon: 90.356, code: "BGD", region: "Asia" },
    { name: "Bhutan", lat: 27.514, lon: 90.434, code: "BTN", region: "Asia" },
    { name: "Brunei", lat: 4.535, lon: 114.728, code: "BRN", region: "Asia" },
    { name: "Cambodia", lat: 12.566, lon: 104.991, code: "KHM", region: "Asia" },
    { name: "China", lat: 35.862, lon: 104.195, code: "CHN", region: "Asia" },
    { name: "Georgia", lat: 42.315, lon: 43.357, code: "GEO", region: "Asia" },
    { name: "India", lat: 20.594, lon: 78.963, code: "IND", region: "Asia" },
    { name: "Indonesia", lat: -0.789, lon: 113.921, code: "IDN", region: "Asia" },
    { name: "Iran", lat: 32.427, lon: 53.688, code: "IRN", region: "Asia" },
    { name: "Iraq", lat: 33.224, lon: 43.679, code: "IRQ", region: "Asia" },
    { name: "Israel", lat: 31.046, lon: 34.852, code: "ISR", region: "Asia" },
    { name: "Japan", lat: 36.205, lon: 138.253, code: "JPN", region: "Asia" },
    { name: "Jordan", lat: 30.585, lon: 36.239, code: "JOR", region: "Asia" },
    { name: "Kazakhstan", lat: 48.020, lon: 66.924, code: "KAZ", region: "Asia" },
    { name: "Kuwait", lat: 29.311, lon: 47.482, code: "KWT", region: "Asia" },
    { name: "Kyrgyzstan", lat: 41.204, lon: 74.766, code: "KGZ", region: "Asia" },
    { name: "Laos", lat: 19.856, lon: 102.495, code: "LAO", region: "Asia" },
    { name: "Lebanon", lat: 33.855, lon: 35.862, code: "LBN", region: "Asia" },
    { name: "Malaysia", lat: 4.210, lon: 101.976, code: "MYS", region: "Asia" },
    { name: "Maldives", lat: 3.203, lon: 73.221, code: "MDV", region: "Asia" },
    { name: "Mongolia", lat: 46.862, lon: 103.847, code: "MNG", region: "Asia" },
    { name: "Myanmar", lat: 21.914, lon: 95.956, code: "MMR", region: "Asia" },
    { name: "Nepal", lat: 28.394, lon: 84.124, code: "NPL", region: "Asia" },
    { name: "North Korea", lat: 40.339, lon: 127.510, code: "PRK", region: "Asia" },
    { name: "Oman", lat: 21.513, lon: 55.923, code: "OMN", region: "Asia" },
    { name: "Pakistan", lat: 30.375, lon: 69.345, code: "PAK", region: "Asia" },
    { name: "Palestine", lat: 31.952, lon: 35.233, code: "PSE", region: "Asia" },
    { name: "Philippines", lat: 12.879, lon: 121.774, code: "PHL", region: "Asia" },
    { name: "Qatar", lat: 25.354, lon: 51.184, code: "QAT", region: "Asia" },
    { name: "Saudi Arabia", lat: 23.886, lon: 45.079, code: "SAU", region: "Asia" },
    { name: "Singapore", lat: 1.352, lon: 103.820, code: "SGP", region: "Asia" },
    { name: "South Korea", lat: 35.908, lon: 127.767, code: "KOR", region: "Asia" },
    { name: "Sri Lanka", lat: 7.873, lon: 80.772, code: "LKA", region: "Asia" },
    { name: "Syria", lat: 34.802, lon: 38.996, code: "SYR", region: "Asia" },
    { name: "Taiwan", lat: 23.698, lon: 120.961, code: "TWN", region: "Asia" },
    { name: "Tajikistan", lat: 38.861, lon: 71.276, code: "TJK", region: "Asia" },
    { name: "Thailand", lat: 15.870, lon: 100.993, code: "THA", region: "Asia" },
    { name: "Timor-Leste", lat: -8.875, lon: 125.728, code: "TLS", region: "Asia" },
    { name: "Turkey", lat: 38.964, lon: 35.243, code: "TUR", region: "Asia" },
    { name: "Turkmenistan", lat: 38.970, lon: 59.556, code: "TKM", region: "Asia" },
    { name: "United Arab Emirates", lat: 23.424, lon: 53.848, code: "ARE", region: "Asia" },
    { name: "Uzbekistan", lat: 41.377, lon: 64.585, code: "UZB", region: "Asia" },
    { name: "Vietnam", lat: 14.058, lon: 108.277, code: "VNM", region: "Asia" },
    { name: "Yemen", lat: 15.552, lon: 48.516, code: "YEM", region: "Asia" },

    // Europe
    { name: "Albania", lat: 41.153, lon: 20.168, code: "ALB", region: "Europe" },
    { name: "Austria", lat: 47.516, lon: 14.550, code: "AUT", region: "Europe" },
    { name: "Belarus", lat: 53.710, lon: 27.953, code: "BLR", region: "Europe" },
    { name: "Belgium", lat: 50.504, lon: 4.470, code: "BEL", region: "Europe" },
    { name: "Bosnia and Herzegovina", lat: 43.916, lon: 17.679, code: "BIH", region: "Europe" },
    { name: "Bulgaria", lat: 42.734, lon: 25.486, code: "BGR", region: "Europe" },
    { name: "Croatia", lat: 45.100, lon: 15.200, code: "HRV", region: "Europe" },
    { name: "Czech Republic", lat: 49.818, lon: 15.473, code: "CZE", region: "Europe" },
    { name: "Denmark", lat: 56.264, lon: 9.501, code: "DNK", region: "Europe" },
    { name: "Estonia", lat: 58.595, lon: 25.014, code: "EST", region: "Europe" },
    { name: "Finland", lat: 61.924, lon: 25.748, code: "FIN", region: "Europe" },
    { name: "France", lat: 46.228, lon: 2.214, code: "FRA", region: "Europe" },
    { name: "Germany", lat: 51.166, lon: 10.452, code: "DEU", region: "Europe" },
    { name: "Greece", lat: 39.074, lon: 21.824, code: "GRC", region: "Europe" },
    { name: "Hungary", lat: 47.162, lon: 19.503, code: "HUN", region: "Europe" },
    { name: "Iceland", lat: 64.963, lon: -19.021, code: "ISL", region: "Europe" },
    { name: "Ireland", lat: 53.412, lon: -8.244, code: "IRL", region: "Europe" },
    { name: "Italy", lat: 41.872, lon: 12.567, code: "ITA", region: "Europe" },
    { name: "Kosovo", lat: 42.602, lon: 20.903, code: "XKX", region: "Europe" },
    { name: "Latvia", lat: 56.879, lon: 24.603, code: "LVA", region: "Europe" },
    { name: "Lithuania", lat: 55.169, lon: 23.881, code: "LTU", region: "Europe" },
    { name: "Luxembourg", lat: 49.815, lon: 6.130, code: "LUX", region: "Europe" },
    { name: "Moldova", lat: 47.411, lon: 28.370, code: "MDA", region: "Europe" },
    { name: "Montenegro", lat: 42.709, lon: 19.374, code: "MNE", region: "Europe" },
    { name: "Netherlands", lat: 52.133, lon: 5.291, code: "NLD", region: "Europe" },
    { name: "North Macedonia", lat: 41.512, lon: 21.745, code: "MKD", region: "Europe" },
    { name: "Norway", lat: 60.472, lon: 8.469, code: "NOR", region: "Europe" },
    { name: "Poland", lat: 51.919, lon: 19.145, code: "POL", region: "Europe" },
    { name: "Portugal", lat: 39.400, lon: -8.225, code: "PRT", region: "Europe" },
    { name: "Romania", lat: 45.943, lon: 24.967, code: "ROU", region: "Europe" },
    { name: "Russia", lat: 61.524, lon: 105.319, code: "RUS", region: "Europe" },
    { name: "Serbia", lat: 44.017, lon: 21.006, code: "SRB", region: "Europe" },
    { name: "Slovakia", lat: 48.669, lon: 19.699, code: "SVK", region: "Europe" },
    { name: "Slovenia", lat: 46.151, lon: 14.995, code: "SVN", region: "Europe" },
    { name: "Spain", lat: 40.464, lon: -3.749, code: "ESP", region: "Europe" },
    { name: "Sweden", lat: 60.128, lon: 18.643, code: "SWE", region: "Europe" },
    { name: "Switzerland", lat: 46.818, lon: 8.228, code: "CHE", region: "Europe" },
    { name: "Ukraine", lat: 48.380, lon: 31.166, code: "UKR", region: "Europe" },
    { name: "United Kingdom", lat: 55.378, lon: -3.436, code: "GBR", region: "Europe" },

    // North America
    { name: "Belize", lat: 17.190, lon: -88.497, code: "BLZ", region: "North America" },
    { name: "Canada", lat: 56.130, lon: -106.347, code: "CAN", region: "North America" },
    { name: "Costa Rica", lat: 9.749, lon: -83.754, code: "CRI", region: "North America" },
    { name: "Cuba", lat: 21.522, lon: -77.781, code: "CUB", region: "North America" },
    { name: "Dominican Republic", lat: 18.736, lon: -70.163, code: "DOM", region: "North America" },
    { name: "El Salvador", lat: 13.794, lon: -88.897, code: "SLV", region: "North America" },
    { name: "Guatemala", lat: 15.783, lon: -90.231, code: "GTM", region: "North America" },
    { name: "Haiti", lat: 18.971, lon: -72.285, code: "HTI", region: "North America" },
    { name: "Honduras", lat: 15.200, lon: -86.242, code: "HND", region: "North America" },
    { name: "Jamaica", lat: 18.109, lon: -77.298, code: "JAM", region: "North America" },
    { name: "Mexico", lat: 23.635, lon: -102.553, code: "MEX", region: "North America" },
    { name: "Nicaragua", lat: 12.866, lon: -85.207, code: "NIC", region: "North America" },
    { name: "Panama", lat: 8.538, lon: -80.782, code: "PAN", region: "North America" },
    { name: "Puerto Rico", lat: 18.221, lon: -66.590, code: "PRI", region: "North America" },
    { name: "Trinidad and Tobago", lat: 10.692, lon: -61.222, code: "TTO", region: "North America" },
    { name: "United States", lat: 37.091, lon: -95.713, code: "USA", region: "North America" },

    // South America
    { name: "Argentina", lat: -38.416, lon: -63.617, code: "ARG", region: "South America" },
    { name: "Bolivia", lat: -16.290, lon: -63.589, code: "BOL", region: "South America" },
    { name: "Brazil", lat: -14.235, lon: -51.925, code: "BRA", region: "South America" },
    { name: "Chile", lat: -35.675, lon: -71.543, code: "CHL", region: "South America" },
    { name: "Colombia", lat: 4.571, lon: -74.297, code: "COL", region: "South America" },
    { name: "Ecuador", lat: -1.831, lon: -78.183, code: "ECU", region: "South America" },
    { name: "Guyana", lat: 4.861, lon: -58.930, code: "GUY", region: "South America" },
    { name: "Paraguay", lat: -23.443, lon: -58.444, code: "PRY", region: "South America" },
    { name: "Peru", lat: -9.190, lon: -75.015, code: "PER", region: "South America" },
    { name: "Suriname", lat: 3.919, lon: -56.028, code: "SUR", region: "South America" },
    { name: "Uruguay", lat: -32.523, lon: -55.766, code: "URY", region: "South America" },
    { name: "Venezuela", lat: 6.424, lon: -66.590, code: "VEN", region: "South America" },

    // Oceania
    { name: "Australia", lat: -25.274, lon: 133.775, code: "AUS", region: "Oceania" },
    { name: "Fiji", lat: -17.713, lon: 178.065, code: "FJI", region: "Oceania" },
    { name: "New Zealand", lat: -40.901, lon: 174.886, code: "NZL", region: "Oceania" },
    { name: "Papua New Guinea", lat: -6.315, lon: 143.956, code: "PNG", region: "Oceania" },
    { name: "Solomon Islands", lat: -9.645, lon: 160.156, code: "SLB", region: "Oceania" },
    { name: "Vanuatu", lat: -15.377, lon: 166.959, code: "VUT", region: "Oceania" },
];

// ISO3 to ISO2 mapping for World Bank API
export const ISO3_TO_ISO2 = {
    "DZA": "DZ", "AGO": "AO", "BEN": "BJ", "BWA": "BW", "BFA": "BF",
    "BDI": "BI", "CMR": "CM", "CPV": "CV", "CAF": "CF", "TCD": "TD",
    "COM": "KM", "COD": "CD", "DJI": "DJ", "EGY": "EG", "GNQ": "GQ",
    "ERI": "ER", "SWZ": "SZ", "ETH": "ET", "GAB": "GA", "GMB": "GM",
    "GHA": "GH", "GIN": "GN", "GNB": "GW", "CIV": "CI", "KEN": "KE",
    "LSO": "LS", "LBR": "LR", "LBY": "LY", "MDG": "MG", "MWI": "MW",
    "MLI": "ML", "MRT": "MR", "MUS": "MU", "MAR": "MA", "MOZ": "MZ",
    "NAM": "NA", "NER": "NE", "NGA": "NG", "COG": "CG", "RWA": "RW",
    "SEN": "SN", "SLE": "SL", "SOM": "SO", "ZAF": "ZA", "SSD": "SS",
    "SDN": "SD", "TZA": "TZ", "TGO": "TG", "TUN": "TN", "UGA": "UG",
    "ZMB": "ZM", "ZWE": "ZW", "AFG": "AF", "ARM": "AM", "AZE": "AZ",
    "BHR": "BH", "BGD": "BD", "BTN": "BT", "BRN": "BN", "KHM": "KH",
    "CHN": "CN", "GEO": "GE", "IND": "IN", "IDN": "ID", "IRN": "IR",
    "IRQ": "IQ", "ISR": "IL", "JPN": "JP", "JOR": "JO", "KAZ": "KZ",
    "KWT": "KW", "KGZ": "KG", "LAO": "LA", "LBN": "LB", "MYS": "MY",
    "MDV": "MV", "MNG": "MN", "MMR": "MM", "NPL": "NP", "PRK": "KP",
    "OMN": "OM", "PAK": "PK", "PSE": "PS", "PHL": "PH", "QAT": "QA",
    "SAU": "SA", "SGP": "SG", "KOR": "KR", "LKA": "LK", "SYR": "SY",
    "TWN": "TW", "TJK": "TJ", "THA": "TH", "TLS": "TL", "TUR": "TR",
    "TKM": "TM", "ARE": "AE", "UZB": "UZ", "VNM": "VN", "YEM": "YE",
    "ALB": "AL", "AUT": "AT", "BLR": "BY", "BEL": "BE", "BIH": "BA",
    "BGR": "BG", "HRV": "HR", "CZE": "CZ", "DNK": "DK", "EST": "EE",
    "FIN": "FI", "FRA": "FR", "DEU": "DE", "GRC": "GR", "HUN": "HU",
    "ISL": "IS", "IRL": "IE", "ITA": "IT", "XKX": "XK", "LVA": "LV",
    "LTU": "LT", "LUX": "LU", "MDA": "MD", "MNE": "ME", "NLD": "NL",
    "MKD": "MK", "NOR": "NO", "POL": "PL", "PRT": "PT", "ROU": "RO",
    "RUS": "RU", "SRB": "RS", "SVK": "SK", "SVN": "SI", "ESP": "ES",
    "SWE": "SE", "CHE": "CH", "UKR": "UA", "GBR": "GB", "BLZ": "BZ",
    "CAN": "CA", "CRI": "CR", "CUB": "CU", "DOM": "DO", "SLV": "SV",
    "GTM": "GT", "HTI": "HT", "HND": "HN", "JAM": "JM", "MEX": "MX",
    "NIC": "NI", "PAN": "PA", "PRI": "PR", "TTO": "TT", "USA": "US",
    "ARG": "AR", "BOL": "BO", "BRA": "BR", "CHL": "CL", "COL": "CO",
    "ECU": "EC", "GUY": "GY", "PRY": "PY", "PER": "PE", "SUR": "SR",
    "URY": "UY", "VEN": "VE", "AUS": "AU", "FJI": "FJ", "NZL": "NZ",
    "PNG": "PG", "SLB": "SB", "VUT": "VU",
};
